# Generated by Django 5.2.3 on 2025-09-10 03:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('membresia', models.CharField(choices=[('anual', 'Anual'), ('6m', '6 Meses'), ('3m', '3 Meses')], default='anual', max_length=10)),
                ('estado_membresia', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('morosa', 'Morosa'), ('pausada', 'Pausada')], default='activa', max_length=10)),
                ('suspendido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horario', models.DateTimeField()),
                ('cupo', models.PositiveIntegerField()),
                ('personalizada', models.BooleanField(default=False)),
                ('clientes', models.ManyToManyField(related_name='clases', to='admin_gym.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_gym.clase')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.CharField(choices=[('anual', 'Anual'), ('6m', '6 Meses'), ('3m', '3 Meses')], default='anual', max_length=10)),
                ('vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente'), ('Vencido', 'Vencido')], default='Pendiente', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.profesor'),
        ),
    ]
