# Generated by Django 5.2.3 on 2025-09-10 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_gym.clase'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
