# Generated by Django 5.2.3 on 2025-09-12 02:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gym', '0004_credencialpendiente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('fuerza', 'Fuerza'), ('resistencia', 'Resistencia'), ('flexibilidad', 'Flexibilidad'), ('cardio', 'Cardiovascular')], max_length=20)),
                ('grupo_muscular', models.CharField(max_length=50)),
                ('instrucciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('racha', 'Racha de Asistencia'), ('felicitacion', 'Felicitación'), ('motivacional', 'Motivacional'), ('recordatorio', 'Recordatorio')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='permisos_especiales',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('entrenador', 'Entrenador'), ('recepcion', 'Recepción'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='clase',
            name='cupo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='AccesoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=100)),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField()),
                ('motivo_fallo', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('alta_usuario', 'Alta de Usuario'), ('baja_usuario', 'Baja de Usuario'), ('cambio_estado', 'Cambio de Estado'), ('acceso_denegado', 'Acceso Denegado'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.cliente')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.notificaciontemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RecomendacionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estancamiento', 'Estancamiento Detectado'), ('progresion_excesiva', 'Progresión Excesiva'), ('sobrecarga', 'Sobrecarga/Fatiga'), ('cambio_rutina', 'Cambio de Rutina Sugerido')], max_length=20)),
                ('descripcion', models.TextField()),
                ('recomendacion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.cliente')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('objetivo', models.CharField(choices=[('fuerza', 'Fuerza'), ('resistencia', 'Resistencia'), ('perdida_peso', 'Pérdida de Peso'), ('ganancia_muscular', 'Ganancia Muscular'), ('general', 'Acondicionamiento General')], max_length=20)),
                ('es_plantilla', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('series_completadas', models.PositiveIntegerField()),
                ('repeticiones', models.PositiveIntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tiempo', models.PositiveIntegerField(blank=True, help_text='Segundos', null=True)),
                ('rpe', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.cliente')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.ejercicio')),
                ('rutina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_gym.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField()),
                ('repeticiones', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tiempo_descanso', models.PositiveIntegerField(blank=True, help_text='Segundos', null=True)),
                ('orden', models.PositiveIntegerField()),
                ('notas', models.TextField(blank=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='admin_gym.rutina')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RutinaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.cliente')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.rutina')),
            ],
        ),
    ]
