# Generated by Django 5.2.3 on 2025-09-12 03:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gym', '0005_configuracionsistema_ejercicio_notificaciontemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='profesor_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_gym.profesor'),
        ),
        migrations.AddField(
            model_name='registroprogreso',
            name='calidad_sueno',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='registroprogreso',
            name='enfoque_dia',
            field=models.CharField(blank=True, help_text='Ej: Fuerza, Resistencia, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='registroprogreso',
            name='estado_animo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='registroprogreso',
            name='nivel_energia',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='registroprogreso',
            name='visto_por_profesor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ComentarioProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.profesor')),
                ('registro_progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='admin_gym.registroprogreso')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReservaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('tipo_sesion', models.CharField(default='Entrenamiento Personal', max_length=50)),
                ('notas_cliente', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=10)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('notas_profesor', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.cliente')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.profesor')),
            ],
            options={
                'ordering': ['fecha_hora'],
                'unique_together': {('profesor', 'fecha_hora')},
            },
        ),
        migrations.CreateModel(
            name='NotificacionProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nueva_reserva', 'Nueva Reserva'), ('cancelacion', 'Cancelación'), ('progreso_cliente', 'Progreso de Cliente'), ('recordatorio', 'Recordatorio')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.profesor')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_gym.reservaclase')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
