# Generated by Django 5.2.3 on 2025-09-12 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gym', '0006_cliente_profesor_asignado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='00000000-0', help_text='RUT con formato 12345678-9', max_length=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profesor',
            name='rut',
            field=models.CharField(default='11111111-1', help_text='RUT con formato 12345678-9', max_length=12),
        ),
    ]
