# Generated by Django 5.2.3 on 2025-09-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gym', '0007_cliente_rut_cliente_user_profesor_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='00000000-0', help_text='RUT con formato 12345678-9', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='rut',
            field=models.CharField(default='11111111-1', help_text='RUT con formato 12345678-9', max_length=12, unique=True),
        ),
    ]
