# Generated by Django 5.2.3 on 2025-09-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gym', '0008_alter_cliente_rut_alter_profesor_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(help_text='RUT con formato 12345678-9', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='rut',
            field=models.CharField(help_text='RUT con formato 12345678-9', max_length=12, unique=True),
        ),
    ]
