# Generated by Django 5.2.3 on 2025-09-25 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gym', '0009_alter_cliente_rut_alter_profesor_rut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales para el profesor')),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.profesor')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.rutina')),
            ],
            options={
                'unique_together': {('profesor', 'rutina', 'activa')},
            },
        ),
    ]
