# Generated by Django 5.2.3 on 2025-09-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gym', '0010_rutinaprofesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RutinaProfesor',
        ),
    ]
