# Generated by Django 5.2.3 on 2025-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gym', '0011_delete_rutinaprofesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencialpendiente',
            name='password_temporal',
            field=models.CharField(max_length=128),
        ),
    ]
