# Generated by Django 5.2.3 on 2025-10-01 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gym', '0012_alter_credencialpendiente_password_temporal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservaclase',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reservaclase',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='reservaclase',
            name='profesor',
        ),
        migrations.DeleteModel(
            name='NotificacionProfesor',
        ),
        migrations.DeleteModel(
            name='ReservaClase',
        ),
    ]
