# Generated by Django 5.2.3 on 2025-10-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gym', '0013_eliminar_modelos_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
