# Generated by Django 4.2.25 on 2025-10-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gym', '0014_clase_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
