# Generated by Django 4.2.25 on 2025-10-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gym', '0015_cliente_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='descripcion',
        ),
    ]
