# Generated by Django 5.2.7 on 2025-10-17 01:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_gym', '0016_remove_cliente_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='clase',
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horario', models.DateTimeField()),
                ('cupo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion', models.TextField(blank=True)),
                ('personalizada', models.BooleanField(default=False)),
                ('clientes', models.ManyToManyField(related_name='sesiones', to='admin_gym.cliente')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_gym.profesor')),
            ],
            options={
                'verbose_name': 'Sesión de Entrenamiento',
                'verbose_name_plural': 'Sesiones de Entrenamiento',
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_gym.sesion'),
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
    ]
