# Generated by Django 4.2.25 on 2025-10-27 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrenador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrenamientoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio_nombre', models.CharField(max_length=200)),
                ('repeticiones', models.PositiveIntegerField(default=0)),
                ('peso', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('sesion', 'Sesión de Entrenamiento'), ('evaluacion', 'Evaluación'), ('reunion', 'Reunión'), ('descanso', 'Día de Descanso'), ('otro', 'Otro')], default='sesion', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('completado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RecomendacionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aumento_peso', 'Aumento de Peso'), ('aumento_reps', 'Aumento de Repeticiones'), ('cambio_ejercicio', 'Cambio de Ejercicio'), ('descanso', 'Día de Descanso'), ('alerta_estancamiento', 'Alerta de Estancamiento'), ('felicitacion', 'Felicitación por Progreso')], max_length=30)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('accion_sugerida', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('aplicada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aplicacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_creacion', '-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_numero', models.PositiveIntegerField()),
                ('repeticiones_realizadas', models.PositiveIntegerField()),
                ('peso_utilizado', models.CharField(max_length=50)),
                ('rpe_percibido', models.PositiveIntegerField(blank=True, null=True)),
                ('completado', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['serie_numero'],
            },
        ),
        migrations.CreateModel(
            name='RutinaAlumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'entrenador_rutina_alumnos',
            },
        ),
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('duracion_real', models.PositiveIntegerField(blank=True, null=True)),
                ('rating_sesion', models.PositiveIntegerField(blank=True, null=True)),
                ('notas_alumno', models.TextField(blank=True)),
                ('notas_entrenador', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.AlterModelOptions(
            name='detalleejercicio',
            options={'ordering': ['orden', 'grupo_superset']},
        ),
        migrations.AlterModelOptions(
            name='rutina',
            options={'ordering': ['-fecha_actualizacion']},
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='fecha_revision',
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='completado_veces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='descanso',
            field=models.CharField(default='60-90s', max_length=50),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='es_superset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='fecha_mejor_marca',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='grupo_superset',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='incremento_peso',
            field=models.CharField(default='2.5kg', max_length=20),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='incremento_reps',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='mejor_peso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='nombre_ejercicio',
            field=models.CharField(default='Ejercicio sin nombre', max_length=150),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='peso_inicial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='peso_objetivo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='progresion_automatica',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='rpe_objetivo',
            field=models.PositiveIntegerField(blank=True, help_text='RPE 1-10', null=True),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='tempo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='tipo',
            field=models.CharField(choices=[('fuerza', 'Fuerza'), ('cardio', 'Cardio'), ('flexibilidad', 'Flexibilidad'), ('funcional', 'Funcional')], default='fuerza', max_length=20),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='categoria',
            field=models.CharField(default='fuerza', max_length=50),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='exercises/'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='dificultad',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], default='intermedio', max_length=20),
        ),
        migrations.AddField(
            model_name='rutina',
            name='duracion_estimada',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='rutina',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rutina',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='frecuencia_semanal',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='rutina',
            name='notas_entrenador',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='objetivo',
            field=models.CharField(choices=[('fuerza', 'Fuerza'), ('hipertrofia', 'Hipertrofia'), ('resistencia', 'Resistencia'), ('perdida_grasa', 'Pérdida de grasa'), ('funcional', 'Entrenamiento Funcional'), ('rehabilitacion', 'Rehabilitación')], default='hipertrofia', max_length=20),
        ),
        migrations.AddField(
            model_name='rutina',
            name='plantilla_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas_derivadas', to='entrenador.rutina'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='progreso_porcentaje',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rutina',
            name='rating_promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='rutina',
            name='semanas_duracion',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='rutina',
            name='status',
            field=models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('archivada', 'Archivada')], default='activa', max_length=20),
        ),
        migrations.AddField(
            model_name='rutina',
            name='tags',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rutina',
            name='tipo',
            field=models.CharField(choices=[('plantilla', 'Plantilla'), ('personalizada', 'Personalizada'), ('auto_generada', 'Auto-generada')], default='personalizada', max_length=20),
        ),
        migrations.AddField(
            model_name='rutina',
            name='ultima_sesion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='veces_completada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalleejercicio',
            name='ejercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrenador.ejercicio'),
        ),
        migrations.AlterField(
            model_name='detalleejercicio',
            name='repeticiones',
            field=models.CharField(default='10-12', max_length=30),
        ),
        migrations.AlterField(
            model_name='detalleejercicio',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='entrenador.rutina'),
        ),
        migrations.AlterField(
            model_name='detalleejercicio',
            name='series',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name='detalleejercicio',
            index=models.Index(fields=['rutina', 'orden'], name='entrenador__rutina__6d26eb_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleejercicio',
            index=models.Index(fields=['tipo'], name='entrenador__tipo_e4ec76_idx'),
        ),
        migrations.AddIndex(
            model_name='rutina',
            index=models.Index(fields=['entrenador', 'tipo'], name='entrenador__entrena_75488c_idx'),
        ),
        migrations.AddIndex(
            model_name='rutina',
            index=models.Index(fields=['objetivo', 'dificultad'], name='entrenador__objetiv_f2d2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='rutina',
            index=models.Index(fields=['status'], name='entrenador__status_3672fc_idx'),
        ),
        migrations.AddField(
            model_name='sesionentrenamiento',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_entrenamiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesionentrenamiento',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='entrenador.rutina'),
        ),
        migrations.AddField(
            model_name='rutinaalumnos',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenador.rutina'),
        ),
        migrations.AddField(
            model_name='rutinaalumnos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroejercicio',
            name='detalle_ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenador.detalleejercicio'),
        ),
        migrations.AddField(
            model_name='registroejercicio',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='entrenador.sesionentrenamiento'),
        ),
        migrations.AddField(
            model_name='recomendacionsistema',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recomendacionsistema',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='entrenador.rutina'),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrenamientolog',
            name='rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrenamiento_logs', to='entrenador.rutina'),
        ),
        migrations.AddField(
            model_name='entrenamientolog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamiento_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rutina',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='rutinas_asignadas', through='entrenador.RutinaAlumnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rutinaalumnos',
            unique_together={('rutina', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='registroejercicio',
            unique_together={('sesion', 'detalle_ejercicio', 'serie_numero')},
        ),
    ]
