# Generated by Django 5.0.6 on 2025-11-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenador', '0002_entrenamientolog_eventocalendario_and_more'),
        ('entrenador', '0003_add_notas_column'),
    ]

    operations = [
    ]
