# Generated by Django 5.0.6 on 2025-11-07 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenador', '0004_merge_20251107_0119'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('clase', 'Clase'), ('entrenamiento', 'Entrenamiento'), ('evento', 'Evento')], default='clase', max_length=20)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('capacidad', models.PositiveIntegerField(blank=True, help_text='Null = ilimitado', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('publico', models.BooleanField(default=True)),
                ('cancelada', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inscrito', 'Inscrito'), ('rechazado', 'Rechazado')], default='inscrito', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_sesiones', to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='entrenador.clasesesion')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('sesion', 'alumno')},
            },
        ),
    ]
