steps:
  # 1. Compilar la imagen Docker para el servicio del entrenador.
  # Usamos el contexto para apuntar a la subcarpeta /trainer_app.
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/trainer-app-image:latest', # Nombre de la imagen
      './trainer_app' # Directorio de contexto de compilación
    ]

  # 2. Subir la imagen compilada a Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/trainer-app-image:latest']

  # 3. Desplegar la imagen al servicio de Cloud Run.
  # Aquí especificamos la conexión a Cloud SQL y las variables.
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'trainer-app-service', # Nombre del servicio de destino
      '--image', 'gcr.io/$PROJECT_ID/trainer-app-image:latest',
      '--platform', 'managed',
      '--region', 'southamerica-west1',
      '--allow-unauthenticated',
      
      # Conexión a Cloud SQL
      '--add-cloudsql-instances', 'fitspace-478618:southamerica-west1:free-trial-first-project',
      
      # Variables de entorno
      '--set-env-vars', 
        'DB_HOST=/cloudsql/fitspace-478618:southamerica-west1:free-trial-first-project',
        'DB_NAME=fitspace',
        'DB_USER=[TU_USUARIO_BD]',
        'DB_PASSWORD=[TU_PASSWORD_BD]',
        'SECRET_KEY=[TU_CLAVE_SECRETA_DJANGO]',
        'GS_BUCKET_NAME=[TU_BUCKET_GCS]'
    ]
    
# Configuración global para el registro (Logging) - SOLUCIONA EL ERROR ANTERIOR
options:
  # Le dice a Cloud Build que use el servicio Cloud Logging, no un bucket de almacenamiento.
  logging: CLOUD_LOGGING_ONLY 
  
  # Aumentamos el tiempo de espera por si la compilación de Pillow es lenta
  timeout: '1200s'
