# Generated by Django 4.2.25 on 2025-10-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenador_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGymCliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('activo', models.BooleanField()),
                ('fecha_registro', models.DateTimeField()),
                ('membresia', models.CharField(max_length=10)),
                ('estado_membresia', models.CharField(max_length=10)),
                ('suspendido', models.BooleanField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('qr_code', models.CharField(max_length=100)),
                ('qr_image', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('descripcion', models.TextField()),
                ('facebook', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto_perfil', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(max_length=100)),
                ('qr_secret', models.CharField(max_length=32)),
                ('twitter', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_gym_cliente',
                'ordering': ['-fecha_registro'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminGymEjercicio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
                ('grupo_muscular', models.CharField(max_length=50)),
                ('instrucciones', models.TextField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'admin_gym_ejercicio',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminGymEjercicioRutina',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('series', models.PositiveIntegerField()),
                ('repeticiones', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tiempo_descanso', models.PositiveIntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField()),
                ('notas', models.TextField()),
            ],
            options={
                'db_table': 'admin_gym_ejerciciorutina',
                'ordering': ['rutina_id', 'orden'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminGymProfesor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'admin_gym_profesor',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminGymRecomendacionSistema',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('recomendacion', models.TextField()),
                ('estado', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_gym_recomendacionsistema',
                'ordering': ['-fecha_creacion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminGymRutina',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('objetivo', models.CharField(max_length=20)),
                ('es_plantilla', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
                ('activa', models.BooleanField()),
            ],
            options={
                'db_table': 'admin_gym_rutina',
                'ordering': ['-fecha_creacion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminGymRutinaCliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField()),
            ],
            options={
                'db_table': 'admin_gym_rutinacliente',
                'ordering': ['-fecha_asignacion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAppMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_type', models.CharField(choices=[('admin', 'admin'), ('entrenador', 'entrenador'), ('cliente', 'cliente')], max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_app_mapping',
                'ordering': ['user_id', 'app_type'],
                'managed': False,
            },
        ),
    ]
