# Generated by Django 4.2.25 on 2025-10-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenador_app', '0002_admingymcliente_admingymejercicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrenamientoLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ejercicio_nombre', models.CharField(max_length=200)),
                ('repeticiones', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'entrenamiento_log',
                'ordering': ['-fecha'],
                'managed': False,
            },
        ),
    ]
