# Generated by Django 5.0.6 on 2025-11-07 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenador_app', '0003_entrenamientolog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ayuda_general', 'Ayuda General'), ('problema_ejercicio', 'Problema con Ejercicio'), ('dolor_lesion', 'Dolor o Lesión'), ('consulta_rutina', 'Consulta sobre Rutina'), ('emergencia', 'Emergencia')], default='ayuda_general', max_length=20)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_atencion', 'En Atención'), ('resuelto', 'Resuelto')], default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_enviadas', to=settings.AUTH_USER_MODEL)),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entrenador_app_alertaayuda',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_alumno', to=settings.AUTH_USER_MODEL)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_entrenador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entrenador_app_chatconversacion',
                'unique_together': {('alumno', 'entrenador')},
            },
        ),
        migrations.CreateModel(
            name='ChatMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='entrenador_app.chatconversacion')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entrenador_app_chatmensaje',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='databackup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='databackup',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='qualitymetric',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='qualitymetric',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='securityincident',
            name='affected_user',
        ),
        migrations.RemoveField(
            model_name='securityincident',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='securityincident',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='SystemHealth',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='DataBackup',
        ),
        migrations.DeleteModel(
            name='QualityMetric',
        ),
        migrations.DeleteModel(
            name='SecurityIncident',
        ),
        migrations.DeleteModel(
            name='SystemConfiguration',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
