# Generated by Django 4.2.25 on 2025-10-04 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(default=0)),
                ('repeticiones', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_revision', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('peso_levantado_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('series_realizadas', models.PositiveIntegerField(default=0)),
                ('detalle_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenador.detalleejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='plantillas_excel/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenador.ejercicio'),
        ),
        migrations.AddField(
            model_name='detalleejercicio',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenador.rutina'),
        ),
        migrations.CreateModel(
            name='ContadorSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_semana', models.DateField()),
                ('total_series_rutina', models.IntegerField(default=0)),
                ('total_series_semana', models.IntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_asignadas', to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenador.rutina')),
            ],
            options={
                'ordering': ['-fecha_semana'],
                'unique_together': {('alumno', 'rutina', 'fecha_semana')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('entrenador', 'fecha')},
            },
        ),
    ]
