# Generated by Django 4.2.25 on 2025-10-04 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrenador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('sesion', 'Sesión de Entrenamiento'), ('evaluacion', 'Evaluación'), ('reunion', 'Reunión'), ('descanso', 'Día de Descanso'), ('otro', 'Otro')], default='sesion', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('completado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_asignados', to=settings.AUTH_USER_MODEL)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
