# Generated by Django 4.2.25 on 2025-10-04 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitoBueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('agua', 'Tomar Agua'), ('sueno', 'Dormir Bien'), ('ejercicio', 'Ejercicio Extra'), ('meditacion', 'Meditación'), ('lectura', 'Lectura'), ('otro', 'Otro')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('meta_diaria', models.IntegerField(default=1)),
                ('unidad', models.CharField(default='veces', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.perfilalumno')),
            ],
        ),
        migrations.CreateModel(
            name='HabitoMalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alimentacion', 'Mala Alimentación'), ('sueno', 'Mal Sueño'), ('procrastinacion', 'Procrastinación'), ('sedentarismo', 'Sedentarismo'), ('estres', 'Manejo del Estrés'), ('otro', 'Otro')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.perfilalumno')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroHabitoMalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('intensidad', models.IntegerField(choices=[(1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], default=1)),
                ('descripcion_situacion', models.TextField()),
                ('reflexion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.habitomalo')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHabitoBueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField(default=1)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.habitobueno')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('habito', 'fecha')},
            },
        ),
    ]
