# Generated by Django 4.2.25 on 2025-10-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_habitobueno_habitomalo_registrohabitomalo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeMotivacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('asistencia', 'Asistencia'), ('habitos', 'Hábitos'), ('progreso', 'Progreso'), ('motivacion', 'Motivación'), ('salud_mental', 'Salud Mental')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('prioridad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('accion_sugerida', models.CharField(blank=True, max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.perfilalumno')),
            ],
            options={
                'ordering': ['-prioridad', '-fecha_envio'],
            },
        ),
    ]
