# Generated by Django 4.2.25 on 2025-10-04 21:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_mensajemotivacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('empuje', 'Tren Superior - Empuje'), ('traccion', 'Tren Superior - Tracción'), ('piernas', 'Tren Inferior'), ('core', 'Núcleo (Core)')], max_length=20)),
                ('descripcion', models.TextField()),
                ('maquina_requerida', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=50)),
                ('musculos_principales', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('series', models.IntegerField(default=1)),
                ('repeticiones', models.IntegerField(default=1)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.perfilalumno')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.ejercicio')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
