# Generated by Django 4.2.25 on 2025-10-04 21:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_ejercicio_registroejercicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('peso', 'Peso Corporal'), ('fuerza', 'Fuerza'), ('resistencia', 'Resistencia'), ('habitos', 'Hábitos'), ('general', 'General')], max_length=20)),
                ('fecha_objetivo', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('valor_objetivo', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.perfilalumno')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('valor_actual', models.CharField(max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='alumno.meta')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AccionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='alumno.meta')),
            ],
            options={
                'ordering': ['completada', '-fecha_creacion'],
            },
        ),
    ]
