# Generated by Django 4.2.25 on 2025-10-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0005_meta_progresometa_accionmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilalumno',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
