# Generated by Django 4.2.25 on 2025-10-24 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumno', '0007_informacionalumno'),
        ('entrenador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('objetivo', models.CharField(choices=[('fuerza', 'Fuerza'), ('hipertrofia', 'Ganancia Muscular'), ('resistencia', 'Resistencia'), ('perdida_grasa', 'Pérdida de Grasa'), ('funcional', 'Entrenamiento Funcional')], max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('series', models.PositiveIntegerField()),
                ('repeticiones', models.PositiveIntegerField()),
                ('descanso', models.PositiveIntegerField(help_text='Tiempo de descanso en segundos')),
                ('notas', models.TextField(blank=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrenador.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='alumno.rutina')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
