# Generated by Django 4.2.25 on 2025-11-08 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrenador', '0006_remove_chat_models'),
        ('alumno', '0009_progresofisico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioRutinaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('series', models.PositiveIntegerField()),
                ('repeticiones', models.CharField(max_length=30)),
                ('peso', models.CharField(blank=True, max_length=50)),
                ('descanso', models.CharField(default='60s', max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('ejercicio_entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrenador.detalleejercicio')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RutinaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('objetivo', models.CharField(choices=[('fuerza', 'Fuerza'), ('hipertrofia', 'Ganancia Muscular'), ('resistencia', 'Resistencia'), ('perdida_grasa', 'Pérdida de Grasa'), ('funcional', 'Entrenamiento Funcional')], max_length=20)),
                ('tipo', models.CharField(choices=[('asignada', 'Asignada por Entrenador'), ('personal', 'Rutina Personal')], max_length=20)),
                ('dia_asignado', models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, null=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='alumno.perfilalumno')),
                ('asignada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rutina_entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entrenador.rutina')),
            ],
            options={
                'ordering': ['dia_asignado', '-fecha_creacion'],
            },
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='creado_por',
        ),
        migrations.DeleteModel(
            name='EjercicioRutina',
        ),
        migrations.DeleteModel(
            name='Rutina',
        ),
        migrations.AddField(
            model_name='ejerciciorutinaalumno',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='alumno.rutinaalumno'),
        ),
    ]
