# Generated by Django 4.2.25 on 2025-11-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0010_ejerciciorutinaalumno_rutinaalumno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejerciciorutinaalumno',
            name='ejercicio_entrenador',
        ),
    ]
