# Generated by Django 5.0.6 on 2025-11-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_add_fields_mensajemotivacional'),
        ('alumno', '0011_remove_ejerciciorutinaalumno_ejercicio_entrenador'),
    ]

    operations = [
    ]
