# Generated by Django 5.0.6 on 2025-11-20 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0012_merge_20251112_2243'),
        ('entrenador', '0006_remove_chat_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciorutinaalumno',
            name='ejercicio_entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios_alumnos', to='entrenador.detalleejercicio'),
        ),
        migrations.AlterField(
            model_name='mensajemotivacional',
            name='nivel',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('danger', 'Danger')], default='info', max_length=10),
        ),
    ]
